### PR TITLE
Fix assignments generator

### PR DESCRIPTION
**Pull request by matedabis**
Fixing assignments generator to be up to date with binary operators generator.

### CODE REVIEW

**Review by loki04 — CHANGES_REQUESTED** [review]
Please, split the patch to two different PR:
1. 'utils' and import fixes
2. renaming and debugging

**Comment by matedabis** [comment]
I split the PR into 2 PR-s, debugging, and adding message. #14

**Review by rerobika — APPROVED** [review]
LGTM

**Review by loki04 — APPROVED** [review]
LGTM

**Pull request merged**
